# Generated by Django 5.2.6 on 2025-11-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=50)),
                ('ContactNumber', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=50)),
                ('Locality', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('Experience', models.IntegerField(max_length=50)),
                ('Current_working_Place', models.CharField(max_length=50)),
                ('status', models.BooleanField(default='False', max_length=25)),
            ],
        ),
    ]
