# Generated by Django 5.2.6 on 2025-11-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_admin', '0002_doctor_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_registration',
            name='Password',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
