# Generated by Django 5.2.1 on 2026-01-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('P_admin', '0003_alter_doctor_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_registration',
            name='ContactNumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
