# Generated by Django 5.2.6 on 2025-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentName', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=75)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('ChildName', models.CharField(max_length=25)),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(max_length=10)),
                ('standard', models.IntegerField(max_length=2)),
                ('syllabus', models.CharField(max_length=10)),
            ],
        ),
    ]
