# Generated by Django 5.2.7 on 2026-01-10 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='standard',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disorder', models.CharField(choices=[('dysgraphia', 'Dysgraphia'), ('discalculia', 'Discalculia'), ('dyslexia', 'Dyslexia')], max_length=20)),
                ('total_questions', models.IntegerField(default=10)),
                ('answered_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('unanswered_count', models.IntegerField(default=0)),
                ('marks_per_question', models.IntegerField(default=5)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(default='BORDERLINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_registration')),
            ],
            options={
                'unique_together': {('user', 'disorder')},
            },
        ),
    ]
